apiVersion: v1
kind: Service
metadata:
  labels:
    app: loader-service-app
  name: loader-service
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: loader-service-app
  type: NodePort
