apiVersion: v1
kind: Service
metadata:
  labels:
    app: loader-ms-app
  name: loader-ms 
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: loader-ms-app
  type: NodePort
status:
  loadBalancer: {}