apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlloader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlloader
  template:
    metadata:
      labels:
        app: mysqlloader
    spec:
      containers:
      - name: mysqlloader
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage