apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      hostname: mysqldb
      containers:
      - name: mysqldb
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: LOADER_DB
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: LOADER_DB
        volumeMounts:
        - name: mysql-persistent-storage-01
          mountPath: /var/lib/mysql
        command: ["tail", "-f", "/dev/null"]  # Override the command to keep the container running
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage-01
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
