apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      hostname: mysqldb
      containers:
      - name: mysqldb
        image: mysql:latest
        ports:
        - containerPort: 3307
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE00
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE00
        - name: MYSQL_DATABASE01
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE01
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi