apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-ms-app
  name: security-ms 
spec:
  ports:
  - port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app: security-ms-app
  type: NodePort
status:
  loadBalancer: {}