apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jobs-worker
  template:
    metadata:
      labels:
        app: jobs-worker
    spec:
      containers:
      - name: jobs-worker
        image: ayobnas/jobs-worker:v3.1
        ports:
        - containerPort: 6565