apiVersion: v1
kind: Service
metadata:
  labels:
    app: action-ms-app
  name: action-ms 
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: action-ms-app
  type: NodePort
status:
  loadBalancer: {}