apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notifications-app
  template:
    metadata:
      labels:
        app: notifications-app
    spec:
      containers:
      - name: notifications-app
        image: ayobnas/notifications-service:v1.0
        ports:
        - containerPort: 7777
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"