apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications-service-app
  name: notifications-service
spec:
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: notifications-service-app
  type: NodePort
status:
  loadBalancer: {}